vars:
    - data_path: "../../data/raw/allMeSH_2021.json"
    - script_loc: "../../grants_tagger_light/training"
    - output_dir: "../../bertmesh_outs/pipeline_test"

stages:
    train:
        cmd: >-
            python ${script_loc}/train.py
            --model_key ""
            --data_path ${data_path}
            --output_dir ${output_dir}
            --max_samples 10
            --per_device_train_batch_size 4
            --per_device_eval_batch_size 4
        deps:
            - ${data_path}
        params:
            - ../../grants_tagger_light/training/cli_args/train_args.py:
                  - BertMeshTrainingArguments
        outs:
            - ${output_dir}/best
